### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by H-A-M-G-E-R**
i haven't tested it much

### CODE REVIEW

**Comment by galoomba1** [comment]
What exactly does this fix?

**Comment by H-A-M-G-E-R** [comment]
non-fissary polytopes with fissary elements are counted as fissary and truncating a polytope where rank != dimension

**Comment by galoomba1** [comment]
What does the `fn update_system` in the first commit do?

I think polytopes with fissary elements are usually considered fissary.

The "exclude hemis" feature is not redundant, as the inradius bounds are inclusive.

**Comment by H-A-M-G-E-R** [comment]
fn update_system is for getting the right number of checkboxes for truncation

**Pull request closed without merging**
